disabled_rules:
  - trailing_whitespace
  - force_cast
  - line_length
  - file_length
  - nesting

excluded:
  - Pods
  - Game/Alamofire # If you want to exclude third-party libraries within Game

included:
  - Game/
  - Sources

