# Fastfile

default_platform(:ios)

platform :ios do
  desc "Authenticate with Apple Developer Portal"
  lane :authenticate do
    match(type: "development", readonly: true) # Use readonly mode to avoid needing to access the Dev Portal
  end

  desc "Run SwiftLint"
  lane :lint do
    # Lint the main app files and the test files
    sh "swiftlint lint GimigoTheGecko GimigoTheGeckoTests GimigoTheGeckoUITests"
  end

  desc "Build and test the app"
  lane :build_and_test do
    match(type: "development", readonly: true) # Ensure readonly mode for provisioning profiles
    build_app(scheme: "GimigoTheGecko", export_method: "development")
    scan(scheme: "GimigoTheGecko", device: "iPhone 12")
  end
end

