default_platform(:ios)

platform :ios do
  desc "Authenticate with Apple Developer Portal"
  lane :authenticate do
    match(type: "development", readonly: true) # Use readonly mode to avoid needing to access the Dev Portal
  end

  desc "Build and test the app"
  lane :build_and_test do
    match(type: "development", readonly: true) # Ensure readonly mode for provisioning profiles
    build_app(
      scheme: "GimigoTheGecko", 
      export_method: "development",
      xcargs: "CODE_SIGNING_ALLOWED=YES -allowProvisioningUpdates"  # Correct usage of xcodebuild args
    )
    scan(scheme: "GimigoTheGecko", device: "iPhone 12")
  end
end

