name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install

      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: |
            Pods
            ~/Library/Caches/CocoaPods
            **/xcuserdata
          key: ${{ runner.os }}-pods-${{ hashFiles('Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint lint --config .swiftlint.yml $(find . -name "*.swift") || true

      - name: Install fastlane
        run: |
          sudo gem install fastlane

      - name: Authenticate with Apple Developer Account
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          fastlane authenticate

      - name: Build and Test
        run: |
          fastlane build_and_test

