name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint lint --config .swiftlint.yml $(find . -name "*.swift") || true

      - name: Install fastlane
        run: |
          brew install fastlane

      - name: Authenticate with Apple Developer Account
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.GITHUB_PAT }}  # Use your PAT token here
        run: |
          fastlane authenticate

      - name: Build and Test
        run: |
          fastlane build_and_test

