name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install CocoaPods
        run: gem install cocoapods
      - name: Install Pods
        run: pod install
      - name: Set Derived Data Permissions
        run: sudo chmod -R 755 /Users/runner/Library/Developer/Xcode/DerivedData/
      - name: Build and Test
        run: |
          xcodebuild clean build -workspace GimigoTheGecko.xcworkspace -scheme GimigoTheGecko -destination 'platform=iOS Simulator,name=iPhone 12' CODE_SIGNING_REQUIRED=NO

