name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby environment
      run: |
        brew install cocoapods
        pod install
      working-directory: .

    - name: Install fastlane
      run: |
        brew install fastlane
      working-directory: .

    - name: Authenticate with App Store Connect
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # This secret should be empty or contain the correct password if any
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTH }} # Use this for GitHub access
        GITHUB_TOKEN: ${{ secrets.MATCH_GIT_TOKEN }} # Use this token for access to GitHub certificates repo
      run: |
        fastlane authenticate
      working-directory: .

    - name: Run SwiftLint
      run: |
        fastlane lint
      working-directory: .

    - name: Build and test the app
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # This secret should be empty or contain the correct password if any
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTH }} # Use this for GitHub access
      run: |
        fastlane build_and_test
      working-directory: .

