Skip to content
Navigation Menu
VeiledStudios
/
gimigothegecko
 
Type / to search
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
.github/workflows/ci.yml
 
Lint Fix #45
Jobs
Run details
Workflow file for this run
.github/workflows/ci.yml at 1fe3c21
 /Users/stephentanevski/Projects/GimigoTheGecko/GimigoTheGecko.xcodeproj
 Check failure on line 1 in .github/workflows/ci.yml

 
GitHub Actions
/ .github/workflows/ci.yml

Invalid workflow file
You have an error in your yaml syntax on line 1
Lint Fix · VeiledStudios/gimigothegecko@1fe3c21 
