name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install

      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: |
            Pods
            ~/Library/Caches/CocoaPods
            **/xcuserdata
          key: ${{ runner.os }}-pods-${{ hashFiles('Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint lint --config .swiftlint.yml **/*.swift

      - name: Ensure Derived Data Directory Exists
        run: mkdir -p /Users/runner/Library/Developer/Xcode/DerivedData/

      - name: Set Derived Data Permissions
        run: sudo chmod -R 755 /Users/runner/Library/Developer/Xcode/DerivedData/

      - name: Authenticate with Apple Developer Account
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          echo $APPLE_APP_SPECIFIC_PASSWORD | xcrun altool --validate-app -f path/to/your/app.ipa -u "$APPLE_ID" -p @env:APPLE_APP_SPECIFIC_PASSWORD

      - name: Build
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          xcodebuild clean build -workspace GimigoTheGecko.xcworkspace -scheme GimigoTheGecko -destination 'platform=iOS Simulator,name=iPhone 12' -allowProvisioningUpdates

      - name: Test
        run: |
          xcodebuild test -workspace GimigoTheGecko.xcworkspace -scheme GimigoTheGecko -destination 'platform=iOS Simulator,name=iPhone 12'

