name: iOS Build and Test

# Define the events that trigger the workflow
on:
  push:                   # Trigger on push events to branches
    branches:
      - main              # Only run this workflow for the 'main' branch
  pull_request:           # Trigger on pull requests
    branches:
      - main
  workflow_dispatch:      # Allows manual triggering of the workflow from the GitHub UI

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby environment
      run: |
        brew install cocoapods
        pod install
      working-directory: .

    - name: Install fastlane
      run: |
        brew install fastlane
      working-directory: .

    - name: Authenticate with App Store Connect
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Add the new password here
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTH }}
        GITHUB_TOKEN: ${{ secrets.MATCH_GIT_TOKEN }}
      run: |
        fastlane authenticate
      working-directory: .

    - name: Run SwiftLint
      run: |
        fastlane lint
      working-directory: .

    - name: Build and test the app
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Add the new password here
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTH }}
      run: |
        fastlane build_and_test
      working-directory: .

